#!/usr/bin/env python3
#
# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#

import sys

try:
    from src import iomanager, json_parser, metrics
except ModuleNotFoundError as e:
    sys.exit(f"fatal: {e}.\nTry 'pip install -r requirements.txt'.")

def main():
    args = iomanager.parse_args()
    if args.from_json is not None:
        results_json = json_parser.read(args.from_json)
    else:
        results, headers = metrics.gather_stats(args)
        results_json = json_parser.generate(args, results, headers)
    iomanager.output_results(args, results_json)

if __name__ == "__main__":
    main()
